Repository Qiskit/qiskit-serverless, pull requests merged in 2022-11, with the labels that each got.

#35 Issue 28 | GH Actions on release
  .dockerignore
  .github/release-drafter.yml
  .github/workflows/client-pypi-release.yml
  .github/workflows/docker-node-image.yml
  .github/workflows/docs.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test_payloads/docker-payload.json
  Makefile
Labels: enhancement

#51 GH Workflows: update release
  .github/workflows/client-pypi-release.yml
Labels: enhancement

#53 Docs update
  docs/index.rst
  docs/tutorials/01_quantum_serverless.ipynb
  docs/tutorials/images/electronic_structure_problem.png
  docs/tutorials/images/qr_demo1.png
  docs/tutorials/images/qr_docs.png
  docs/tutorials/images/qr_repo.png
Labels: documentation

#47 Issue 38 | Enhancement: docker configurations improvements
  infrastructure/docker/Dockerfile-notebook
  infrastructure/docker/Dockerfile-ray-qiskit
  infrastructure/docker/README.md
Labels: enhancement

#60 Bug: client connection
  client/quantum_serverless/quantum_serverless.py
Labels: bug

#62 Issue 58 | Docs: readme example with primitives
  README.md
  client/README.md
  docs/guides/03_runtime_primitives_with_quantum_serverless.ipynb
Labels: documentation

#63 Docs: guide on serverless configuration
  docs/guides/03_configuring-quantum-serverless.ipynb
Labels: documentation

#66 Issue 61 | Add support for async jobs
  client/quantum_serverless/core/job.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/quantum_serverless.py
  client/requirements.txt
  client/tests/test_quantum_serverless.py
  docs/guides/04_run_jobs.ipynb
  docs/guides/job.py
Labels: enhancement

#72 Helm: manager port fix
  infrastructure/helm/quantumserverless/values.yaml
Labels: bug

#77 Issue 68 | Port configuration
  client/quantum_serverless/core/provider.py
  client/tests/test_quantum_serverless.py
  docs/guides/03_configuring-quantum-serverless.ipynb
  docs/guides/04_run_jobs.ipynb
Labels: enhancement

#79 Issue 67 | Integration tests
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/quantum_serverless.py
  client/requirements-dev.txt
  client/tests/core/test_job.py
  client/tests/resources/job.py
  client/tests/resources/test-compose.yml
Labels: enhancement
