Repository Qiskit/qiskit-serverless, pull requests merged in 2023-07, with the labels that each got.

#758 Prevent Listing number from prepending to code captions in quickstart
  docs/conf.py
Labels: documentation

#769 Issue 768 | Gateway: hotfix for update status command
  gateway/api/management/commands/update_jobs_statuses.py
Labels: bug

#808 Hook into version number in metadata when building docs
  docs/conf.py
  docs/requirements-doc.txt
Labels: documentation

#815 Issue 742 | Docs: remove outdated terms
  client/quantum_serverless/core/decorators.py
  docs/development/examples/07_benchmark_program.ipynb
  docs/development/examples/source_files/benchmark.py
Labels: documentation

#816 Issue 741 | Docs: remove deprecated algorithms module
  docs/development/examples/01_vqe.ipynb
  docs/development/examples/02_qaoa.ipynb
  docs/development/examples/source_files/qaoa/qaoa.py
  docs/development/examples/source_files/vqe/vqe.py
Labels: documentation

#819 Issue 774 | Infra: long worker names
  gateway/api/schedule.py
  infrastructure/helm/quantum-serverless/charts/gateway/templates/rayclustertemplate.yaml
Labels: enhancement

#823 822 Fix minor documentation typos
  docs/development/examples/07_benchmark_program.ipynb
  docs/running/notebooks/03_arguments_and_results.ipynb
Labels: documentation

#831 Fix docker link
  docs/quickstart/index.rst
Labels: documentation

#833 Add token to quickstart
  docs/quickstart/index.rst
Labels: documentation

#832 Issue 824 | Gateway: add updated field to jobs
  gateway/api/migrations/0007_job_updated.py
  gateway/api/models.py
Labels: enhancement
