Repository Qiskit/qiskit-serverless, pull requests merged in 2023-02, with the labels that each got.

#158 Repository: setup test suit
  repository/main/urls.py
  repository/tests/__init__.py
  repository/tests/core/__init__.py
  repository/tests/core/test_nested_program.py
  repository/tests/fixtures/initial_data.json
  repository/tox.ini
Labels: enhancement

#146 Client: execution graphs tracing using opentelemetry
  client/quantum_serverless/core/constrants.py
  client/quantum_serverless/core/decorators.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/core/tracing.py
  client/quantum_serverless/quantum_serverless.py
  client/requirements.txt
  client/tests/core/test_decorator.py
  client/tests/core/test_events.py
  docker-compose-dev.yml
  docker-compose.yml
Labels: enhancement

#161 Docs: add OT to docs requirements
  docs/requirements-doc.txt
Labels: bug

#166 API versioning configuration
  repository/api/serializers.py
  repository/api/v1/__init__.py
  repository/api/v1/serializers.py
  repository/api/v1/urls.py
  repository/api/v1/views.py
  repository/api/views.py
  repository/main/settings.py
  repository/main/urls.py
  repository/tests/core/test_v1_nested_program.py
Labels: enhancement

#169 Repository: custom validators
  repository/api/serializers.py
  repository/api/validators/__init__.py
  repository/api/validators/dict_validator.py
  repository/api/validators/list_validator.py
  repository/tests/core/test_v1_nested_program.py
Labels: enhancement

#176 Update manager requirements.txt
  manager/requirements.txt
Labels: enhancement

#165 Issue 94 | Client: deprecate __enter__ in favor of context
  client/quantum_serverless/quantum_serverless.py
  docs/guides/01_run_anything_in_distributed_fashion.ipynb
  docs/guides/02_specific_resource_allocation.ipynb
  docs/guides/03_runtime_primitives_with_quantum_serverless.ipynb
  docs/guides/03_specific_package_installation.ipynb
  docs/guides/04_run_programs.ipynb
  docs/guides/05_get_finished_tasks.ipynb
  docs/guides/06_shared_state.ipynb
  docs/guides/07_working_with_datasets.ipynb
  docs/tutorials/01_quantum_serverless.ipynb
  docs/tutorials/02_tutorial_-_approaches_to_serverless_code_writing.ipynb
  docs/tutorials/03_tutorial_writing_serverless_pacakge_from_scratch.ipynb
  docs/tutorials/04_tutorial_-_converting_existing_code_to_serverless.ipynb
  docs/tutorials/07_benchmark_program.ipynb
  docs/tutorials/source_files/benchmark.py
  docs/tutorials/source_files/electronic_structure_problem.py
Labels: bug

#212 Issue 210 | Repository: file upload
  repository/api/migrations/0004_nestedprogram_artifact.py
  repository/api/models.py
  repository/api/v1/serializers.py
  repository/main/settings.py
  repository/main/urls.py
  repository/tests/core/test_v1_nested_program.py
  repository/tests/fixtures/initial_data.json
Labels: enhancement

#164 Issue 162 | Client: repository integration
  client/quantum_serverless/core/constrants.py
  client/quantum_serverless/core/program.py
  client/quantum_serverless/core/provider.py
  client/tests/core/test_program.py
  client/tests/core/test_program_repository.py
  client/tests/resources/program.tar
  repository/api/views.py
  repository/tests/resources/__init__.py
Labels: enhancement

#233 Issue 207 | Program: json arguments
  client/quantum_serverless/core/program.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/utils/json.py
  client/tests/core/test_program.py
Labels: enhancement

#225 Issue 201 | Repository: swagger
  repository/main/settings.py
  repository/main/urls.py
  repository/requirements.txt
Labels: documentation

#189 Infrastructure: add auth2-proxy sidecar container to ray head pod to add login to ray dashboard
  infrastructure/helm/quantumserverless/README.md
  infrastructure/helm/quantumserverless/templates/keycloakrealm.yaml
  infrastructure/helm/quantumserverless/templates/nginxconfig.yaml
  infrastructure/helm/quantumserverless/templates/rayingress.yaml
  infrastructure/helm/quantumserverless/values.yaml
Labels: enhancement

#245 Citation
  CITATION.cff
Labels: documentation

#238 Image build of repository server
  .github/workflows/image-build-and-push-nightly.yml
  .github/workflows/image-build-and-push.yml
  Makefile
  infrastructure/docker/Dockerfile-repository-server
  infrastructure/docker/README.md
Labels: enhancement
