Repository Qiskit/qiskit-serverless, pull requests merged in 2023-08, with the labels that each got.

#844 Issue 842 | Gateway: do not delete compute resource
  gateway/api/management/commands/free_resources.py
  gateway/api/management/commands/schedule_queued_jobs.py
  gateway/api/management/commands/update_jobs_statuses.py
  gateway/api/migrations/0008_computeresource_active.py
  gateway/api/models.py
  gateway/api/schedule.py
  gateway/tests/api/test_models.py
Labels: enhancement

#864 Issue 853 | Client: fix numpy serialization
  client/quantum_serverless/core/job.py
  client/tests/core/test_job.py
Labels: bug

#873 Issue 872 | Gateway: job stop in any status
  gateway/api/views.py
  gateway/tests/api/test_job.py
  gateway/tests/fixtures/fixtures.json
Labels: bug

#900 Relax Qiskit version constraint
  client/requirements.txt
Labels: enhancement

#903 Version bump 0.4.0
  charts/qs-observability/Chart.yaml
  charts/quantum-serverless/Chart.lock
  charts/quantum-serverless/Chart.yaml
  charts/quantum-serverless/charts/gateway/Chart.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
  charts/quantum-serverless/charts/jupyter/Chart.yaml
  charts/quantum-serverless/charts/repository/Chart.yaml
  charts/quantum-serverless/values-ibm.yaml
  charts/quantum-serverless/values.yaml
  client/quantum_serverless/VERSION.txt
  docker-compose.yml
  docs/deployment/cloud.rst
  docs/deployment/local.rst
Labels: release

#916 Fix charts lint errors
  .github/actions/helm-lint/action.yml
  charts/qs-observability/Chart.yaml
  charts/qs-observability/values.yaml
  charts/quantum-serverless/Chart.yaml
  charts/quantum-serverless/values.yaml
  ct.yml
Labels: bug

#913 disable trace when it is disabled
  charts/quantum-serverless/charts/gateway/templates/rayclustertemplate.yaml
  client/quantum_serverless/core/constants.py
  client/quantum_serverless/core/tracing.py
Labels: bug

#908 Experimental new program interface
  client/quantum_serverless/__init__.py
  client/quantum_serverless/core/__init__.py
  client/quantum_serverless/core/constants.py
  client/quantum_serverless/core/decorators.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/quantum_serverless.py
  client/requirements.txt
  docs/running/notebooks/06_running_programs_using_decorators.ipynb
  docs/running/notebooks/source_files/circuit_utils.py
Labels: enhancement, project: client

#920 Increase max number of renovate updates
  renovate.json
Labels: enhancement

#925 Version bump 0.5.0
  .github/workflows/release-pull-request.yml
  charts/qs-observability/Chart.lock
  charts/qs-observability/Chart.yaml
  charts/quantum-serverless/Chart.lock
  charts/quantum-serverless/Chart.yaml
  charts/quantum-serverless/charts/gateway/Chart.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
  charts/quantum-serverless/charts/jupyter/Chart.yaml
  charts/quantum-serverless/charts/repository/Chart.yaml
  charts/quantum-serverless/values-ibm.yaml
  charts/quantum-serverless/values.yaml
  client/quantum_serverless/VERSION.txt
  docker-compose.yml
  docs/deployment/cloud.rst
  docs/deployment/local.rst
Labels: release

#911 fix certificate contents
  charts/quantum-serverless/charts/gateway/templates/raycertgen.yaml
  charts/quantum-serverless/charts/gateway/templates/rayclustertemplate.yaml
Labels: bug
