Repository Qiskit/qiskit-serverless, pull requests merged in 2023-06, with the labels that each got.

#570 Gateway: fair share scheduling and resource limitation
  docker-compose-dev.yml
  docker-compose.yml
  gateway/README.md
  gateway/api/apps.py
  gateway/api/management/commands/free_resources.py
  gateway/api/management/commands/schedule_queued_jobs.py
  gateway/api/management/commands/update_jobs_statuses.py
  gateway/api/migrations/0003_remove_computeresource_users_computeresource_owner_and_more.py
  gateway/api/migrations/0004_alter_computeresource_owner.py
  gateway/api/migrations/0005_alter_program_artifact.py
  gateway/api/migrations/0006_job_env_vars.py
  gateway/api/models.py
  gateway/api/ray.py
  gateway/api/schedule.py
  gateway/api/signals.py
  gateway/api/views.py
  gateway/entrypoint.sh
  gateway/main/settings.py
  gateway/probes/views.py
  gateway/requirements-dev.txt
  gateway/scripts/scheduler.sh
  gateway/tests/api/test_ray.py
  gateway/tests/api/test_schedule.py
  gateway/tests/fixtures/schedule_fixtures.json
  gateway/tests/probes/test_probes.py
  infrastructure/docker/Dockerfile-gateway
  infrastructure/helm/quantumserverless/charts/gateway/templates/deployment.yaml
  infrastructure/helm/quantumserverless/charts/gateway/values.yaml
  infrastructure/helm/quantumserverless/templates/pvcs.yaml
  infrastructure/helm/quantumserverless/values-ibm.yaml
  infrastructure/helm/quantumserverless/values.yaml
Labels: enhancement, project: gateway

#654 Issue 602 | Tracing: broken client
  docker-compose-dev.yml
  docker-compose.yml
Labels: bug

#660 Issue 581 | Tests: warnings
  client/pyproject.toml
  client/tests/core/test_decorator.py
  client/tests/core/test_program.py
  client/tests/library/test_transpiler.py
  client/tests/serializers/test_serializers.py
Labels: bug

#675 Add optional pre install step to quickstart
  docs/quickstart/index.rst
Labels: documentation

#671 Remove deprecated electronic structure problem example
  docs/development/examples/06_electronic_structure_problem.ipynb
  docs/development/examples/source_files/electronic_structure_problem.py
  docs/quickstart/index.rst
  infrastructure/docker/Dockerfile-notebook
Labels: documentation, enhancement

#681 Issue 680 | Client: programs widget
  client/quantum_serverless/core/job.py
  client/quantum_serverless/quantum_serverless.py
  client/quantum_serverless/visualizaiton/__init__.py
  client/quantum_serverless/visualizaiton/widget.py
  client/requirements.txt
  gateway/api/v1/serializers.py
  gateway/api/views.py
Labels: enhancement

#711 add break at retry exceeded
  gateway/api/ray.py
Labels: bug, priority: high

#718 Bug: scheduler hanging compute resources, doc security context
  gateway/api/schedule.py
  infrastructure/helm/quantumserverless/charts/gateway/templates/deployment.yaml
  infrastructure/helm/quantumserverless/templates/pvcs.yaml
Labels: bug

#723 Issue 719 | Logging: better format and messages
  gateway/api/authentication.py
  gateway/api/management/commands/free_resources.py
  gateway/api/management/commands/schedule_queued_jobs.py
  gateway/api/management/commands/update_jobs_statuses.py
  gateway/api/ray.py
  gateway/api/schedule.py
  gateway/api/views.py
  gateway/main/settings.py
Labels: enhancement

#726 Issue 700 | Client: UX improvements
  client/quantum_serverless/core/constants.py
  client/quantum_serverless/core/job.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/utils/json.py
Labels: enhancement
