Repository Qiskit/qiskit-serverless, pull requests merged in 2023-11, with the labels that each got.

#1067 Issue 1028 | Docs: make sphinx build local docs + add save result notes
  client/quantum_serverless/core/__init__.py
  client/quantum_serverless/core/job.py
  client/quantum_serverless/core/pattern.py
  docs/index.rst
  docs/requirements-doc.txt
  tox.ini
Labels: bug

#1070 Bump helm chart-testing-action
  .github/actions/helm-lint/action.yaml
Labels: bug

#1060 Client: url constant
  client/quantum_serverless/core/constants.py
Labels: project: client

#1074 add SamplerResult / EstimatorResult serialization
  client/quantum_serverless/serializers/program_serializers.py
Labels: feature

#1062 Translate all job statuses to Qiskit terminology in client
  README.md
  client/README.md
  client/quantum_serverless/core/job.py
  client/tests/core/test_pattern.py
  client/tests/utils.py
Labels: on-hold feature for release, release candidate

#1080 Fix readme links
  README.md
Labels: documentation

#1085 Add worker configuration
  charts/quantum-serverless/charts/gateway/templates/deployment.yaml
  charts/quantum-serverless/charts/gateway/templates/rayclustertemplate.yaml
  client/quantum_serverless/__init__.py
  client/quantum_serverless/core/__init__.py
  client/quantum_serverless/core/job.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/quantum_serverless.py
  gateway/README.md
  gateway/api/migrations/0011_jobconfig_job_config.py
  gateway/api/models.py
  gateway/api/ray.py
  gateway/api/schedule.py
  gateway/api/serializers.py
  gateway/api/v1/serializers.py
  gateway/api/views.py
  gateway/main/settings.py
  gateway/tests/api/test_serializer.py
  gateway/tests/api/test_v1_program.py
Labels: enhancement, project: client, project: gateway

#963 add filter option to logs
  client/quantum_serverless/core/job.py
  client/tests/core/test_job.py
Labels: on-hold feature for release

#1077 Add python_version to the Configuration
  Makefile
  charts/quantum-serverless/charts/gateway/templates/deployment.yaml
  charts/quantum-serverless/charts/gateway/templates/rayclustertemplate.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
  client/quantum_serverless/core/job.py
  gateway/api/migrations/0011_jobconfig_job_config.py
  gateway/api/migrations/0012_jobconfig_python_version.py
  gateway/api/models.py
  gateway/api/ray.py
  gateway/api/serializers.py
  gateway/main/settings.py
Labels: on-hold feature for release

#1096 Setup log level depending of the environment
  gateway/main/settings.py
Labels: enhancement

#1116 Gateway: fix note image selection
  gateway/api/ray.py
  gateway/main/settings.py
Labels: bug

#1125 Helm keycloak rollback
  charts/quantum-serverless/Chart.lock
  charts/quantum-serverless/Chart.yaml
  renovate.json
Labels: bug
