Repository Qiskit/qiskit-serverless, pull requests merged in 2023-10, with the labels that each got.

#1043 Issue 1040 | Gateway: update logs
  gateway/api/management/commands/update_jobs_statuses.py
Labels: bug

#1047 Bug: notebook deps
  client/requirements-notebook.txt
Labels: bug

#1041 Issue 1036 | Add program upload
  client/quantum_serverless/core/job.py
  client/quantum_serverless/core/program.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/quantum_serverless.py
  client/quantum_serverless/visualizaiton/widget.py
  docs/getting_started/experimental/file_download.ipynb
  docs/getting_started/experimental/source_files/program.py
  docs/getting_started/experimental/upload_program.ipynb
  gateway/api/management/commands/schedule_queued_jobs.py
  gateway/api/schedule.py
  gateway/api/serializers.py
  gateway/api/utils.py
  gateway/api/views.py
  gateway/tests/api/test_schedule.py
  gateway/tests/api/test_utils.py
Labels: enhancement

#1052 Issue 1035 | Deprecate QuantumServerless class
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/quantum_serverless.py
  docs/examples/01_vqe.ipynb
  docs/examples/02_qaoa.ipynb
  docs/getting_started/basic/01_running_program.ipynb
  docs/getting_started/basic/02_arguments_and_results.ipynb
  docs/getting_started/basic/03_dependencies.ipynb
  docs/getting_started/basic/04_distributed_workloads.ipynb
  docs/getting_started/basic/05_retrieving_past_results.ipynb
  docs/getting_started/experimental/file_download.ipynb
  docs/getting_started/experimental/running_programs_using_decorators.ipynb
  docs/getting_started/experimental/upload_program.ipynb
  docs/migration/migration_from_qiskit_runtime_programs.ipynb
Labels: documentation

#1054 Version bump 0.6.6
  charts/qs-observability/Chart.yaml
  charts/quantum-serverless/Chart.lock
  charts/quantum-serverless/Chart.yaml
  charts/quantum-serverless/charts/gateway/Chart.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
  charts/quantum-serverless/charts/jupyter/Chart.yaml
  charts/quantum-serverless/charts/repository/Chart.yaml
  charts/quantum-serverless/values.yaml
  client/quantum_serverless/VERSION.txt
  docker-compose.yaml
  docs/deployment/cloud.rst
Labels: release

#1057 Client + docs: rename `Program`
  client/README.md
  client/quantum_serverless/__init__.py
  client/quantum_serverless/core/__init__.py
  client/quantum_serverless/core/decorators.py
  client/quantum_serverless/core/job.py
  client/quantum_serverless/core/pattern.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/quantum_serverless.py
  client/quantum_serverless/visualizaiton/widget.py
  client/tests/core/test_pattern.py
  client/tests/core/test_program_repository.py
  client/tests/serializers/test_program_serializers.py
  docs/examples/01_vqe.ipynb
  docs/examples/02_qaoa.ipynb
  docs/getting_started/basic/01_running_program.ipynb
  docs/getting_started/basic/02_arguments_and_results.ipynb
  docs/getting_started/basic/03_dependencies.ipynb
  docs/getting_started/basic/04_distributed_workloads.ipynb
  docs/getting_started/basic/05_retrieving_past_results.ipynb
  docs/getting_started/basic/source_files/pattern.py
  docs/getting_started/basic/source_files/pattern_with_arguments.py
  docs/getting_started/basic/source_files/pattern_with_dependencies.py
  docs/getting_started/basic/source_files/pattern_with_parallel_workflow.py
  docs/getting_started/experimental/file_download.ipynb
  docs/getting_started/experimental/running_programs_using_decorators.ipynb
  docs/migration/migration_from_qiskit_runtime_programs.ipynb
  docs/migration/src/migrated_pattern.py
Labels: documentation

#1059 Issue 1058 | Gateway: allow nested fields verification
  gateway/api/authentication.py
  gateway/main/settings.py
  gateway/tests/api/test_authentication.py
Labels: feature

#1029 LocalProvider
  client/quantum_serverless/__init__.py
  client/quantum_serverless/core/__init__.py
  client/quantum_serverless/core/job.py
  client/quantum_serverless/core/provider.py
Labels: feature
