Repository Qiskit/qiskit-serverless, pull requests merged in 2023-01, with the labels that each got.

#93 Issue 92 | Benchmark program for resources stress tests
  docs/tutorials/07_benchmark_program.ipynb
  docs/tutorials/images/benchmark_program.png
  docs/tutorials/source_files/benchmark.py
Labels: documentation, enhancement

#101 Issue 96 | Client: ability to stop jobs
  client/quantum_serverless/core/job.py
  client/tests/core/test_program.py
Labels: enhancement

#102 Docs: guide on working with large datasets
  client/requirements.txt
  docs/guides/07_working_with_datasets.ipynb
Labels: documentation

#108 Issue 106 | Docs: add state to groundstate demo
  docs/guides/04_run_programs.ipynb
  docs/tutorials/06_electronic_structure_problem.ipynb
  docs/tutorials/source_files/electronic_structure_problem.py
Labels: documentation

#123 Issue 120 | Readme: update example
  README.md
  client/quantum_serverless/core/program.py
  docs/guides/06_shared_state.ipynb
Labels: documentation

#124 Issue 110 | Manager: remove cluster create and delete
  manager/Dockerfile
  manager/manager/app.py
  manager/manager/cluster_dao.py
  manager/manager/config.py
  manager/tests/test_app.py
  manager/tests/test_cluster_dao.py
Labels: bug

#125 Docs: infrastructure guide from zero to hero
  README.md
  docs/guides/03_configuring-quantum-serverless.ipynb
  docs/guides/08_multi_cloud_deployment.rst
  infrastructure/readme.md
Labels: documentation
