Repository Qiskit/qiskit-serverless, pull requests merged in 2023-09, with the labels that each got.

#896 Issue 843 | Files: download files saved during Program execution
  client/quantum_serverless/core/files.py
  client/quantum_serverless/core/provider.py
  client/quantum_serverless/quantum_serverless.py
  client/requirements.txt
  docs/development/guides/08_file_download.ipynb
  docs/development/guides/src/produce_files.py
  gateway/api/utils.py
  gateway/api/v1/urls.py
  gateway/api/v1/views.py
  gateway/api/views.py
  gateway/tests/api/test_files.py
  gateway/tests/resources/fake_media/test_user/artifact.tar
  gateway/tests/resources/fake_media/test_user/non_tar_file.txt
  gateway/tests/resources/fake_media/test_user_2/artifact_2.tar
Labels: enhancement

#937 Version bump 0.6.0
  charts/qs-observability/Chart.yaml
  charts/quantum-serverless/Chart.lock
  charts/quantum-serverless/Chart.yaml
  charts/quantum-serverless/charts/gateway/Chart.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
  charts/quantum-serverless/charts/jupyter/Chart.yaml
  charts/quantum-serverless/charts/repository/Chart.yaml
  charts/quantum-serverless/values-ibm.yaml
  charts/quantum-serverless/values.yaml
  client/quantum_serverless/VERSION.txt
  docker-compose.yml
  docs/deployment/cloud.rst
  docs/deployment/local.rst
Labels: release

#928 Improve secrets support
  .github/workflows/helm-verify.yml
  charts/quantum-serverless/charts/gateway/templates/deployment.yaml
  charts/quantum-serverless/charts/gateway/templates/django-secret.yaml
  charts/quantum-serverless/charts/gateway/templates/rayclustertemplate.yaml
  charts/quantum-serverless/charts/gateway/templates/secret-key.yaml
  charts/quantum-serverless/charts/gateway/templates/secret-psql.yaml
  charts/quantum-serverless/charts/gateway/templates/secret-superuser.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
  charts/quantum-serverless/templates/pvcs.yaml
  charts/quantum-serverless/values-ibm.yaml
  charts/quantum-serverless/values.yaml
Labels: enhancement

#955 Renovate configuration for bitnami packages
  ct.yml
  renovate.json
Labels: enhancement

#958 Gateway: handle delete cluster not found error
  gateway/api/ray.py
Labels: bug

#962 Version bump 0.6.1
  charts/qs-observability/Chart.yaml
  charts/quantum-serverless/Chart.lock
  charts/quantum-serverless/Chart.yaml
  charts/quantum-serverless/charts/gateway/Chart.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
  charts/quantum-serverless/charts/jupyter/Chart.yaml
  charts/quantum-serverless/charts/repository/Chart.yaml
  charts/quantum-serverless/values-ibm.yaml
  charts/quantum-serverless/values.yaml
  client/quantum_serverless/VERSION.txt
  docker-compose.yml
  docs/deployment/cloud.rst
  docs/deployment/local.rst
Labels: release

#965 Fix helm port value
  charts/quantum-serverless/charts/gateway/templates/secret-psql.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
Labels: bug

#964 Issue 946 | Optimistic lock
  gateway/api/management/commands/update_jobs_statuses.py
  gateway/api/migrations/0010_job_version.py
  gateway/api/models.py
  gateway/api/schedule.py
  gateway/api/utils.py
  gateway/api/views.py
  gateway/requirements.txt
Labels: bug

#966 Version bump 0.6.2
  charts/qs-observability/Chart.yaml
  charts/quantum-serverless/Chart.lock
  charts/quantum-serverless/Chart.yaml
  charts/quantum-serverless/charts/gateway/Chart.yaml
  charts/quantum-serverless/charts/gateway/values.yaml
  charts/quantum-serverless/charts/jupyter/Chart.yaml
  charts/quantum-serverless/charts/repository/Chart.yaml
  charts/quantum-serverless/values-ibm.yaml
  charts/quantum-serverless/values.yaml
  client/quantum_serverless/VERSION.txt
  docker-compose.yml
  docs/deployment/cloud.rst
  docs/deployment/local.rst
Labels: release

#918 Unify yaml extension
  .dockerignore
  .github/actions/docker-vscan/action.yaml
  .github/actions/helm-lint/action.yaml
  .github/actions/icr-build-and-push-images/action.yaml
  .github/release-drafter.yaml
  .github/workflows/client-pypi-release.yaml
  .github/workflows/docker-build.yaml
  .github/workflows/docker-verify.yaml
  .github/workflows/docs-verify.yaml
  .github/workflows/helm-verify.yaml
  .github/workflows/icr-image-build-and-push.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release-pull-request.yaml
  CONTRIBUTING.md
  client/tests/core/test_program.py
  client/tests/resources/test-compose.yaml
  ct.yaml
  docker-compose-dev.yaml
  docker-compose.yaml
  docs/deployment/cloud.rst
Labels: enhancement

#983 Fix release-drafter action
  .github/workflows/release-drafter.yml
Labels: bug
